/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    base
    kotlin("jvm") version "1.4.10" apply false
}

allprojects {
    repositories {
        jcenter() 
    }
}

subprojects {
    version = "1.0"
}

dependencies {
    subprojects.forEach {
        archives(it)
    }
}