/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    `java-library`
    kotlin("jvm")
}

dependencies {
    implementation(project(":domain"))
    implementation("com.squareup.retrofit2:retrofit:2.9.0")
    implementation("com.squareup.retrofit2:converter-moshi:2.9.0")
}
