/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    `java-library`
    kotlin("jvm")
}

dependencies {
}