/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    application
    kotlin("jvm")
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":infra"))
    implementation(kotlin("stdlib"))

    testImplementation(kotlin("test-common"))
    testImplementation(kotlin("test-annotations-common"))
    testImplementation(kotlin("test-junit"))
}

application {
    // Define the main class for the application.
    mainClassName = "com.cinema.app.AppKt"
}
