/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
plugins {
    application
    kotlin("jvm")
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":infra"))

    val koin_version = "2.1.6"
    implementation("org.koin:koin-core:$koin_version")
    implementation("org.koin:koin-core-ext:$koin_version")
    implementation("org.koin:koin-test:$koin_version")
}

application {
    // Define the main class for the application.
    mainClassName = "com.cinema.app.AppKt"
}
