/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cinema.domain

import org.amshove.kluent.`should be equal to`
import org.amshove.kluent.should
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        classUnderTest.someLibraryMethod() `should be equal to` true
    }
}
